name: CI

on:
  push:
    branches:
    - master
    - release/*

jobs:
  build_dotnetheroku:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - name: Build and deploy the Docker image
      env: 
        HEROKU_API_KEY: d7b52093-3747-406b-9c55-d53ec8afd31d
        APP_NAME: ${{ 'jmsapi' }}
      run: |
        docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME
